repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/hadolint/hadolint
    rev: "v2.12.0"
    hooks:
      - id: hadolint-docker
        args:
          - --ignore
          - DL3008
          - --ignore
          - DL3033
          - --ignore
          - DL3041
          - --failure-threshold
          - warning
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: "0.23.0"
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
